//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobhundClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApply
    {
        public int JobApplyId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime JobApplyDateTime { get; set; }
        public int PostJobId { get; set; }
    }
}
