//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobhundClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRequirement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobRequirement()
        {
            this.JobRequirementDetails = new HashSet<JobRequirementDetail>();
        }
    
        public int JobRequirementId { get; set; }
        public string JobRequirementTitle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRequirementDetail> JobRequirementDetails { get; set; }
    }
}
