//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobhundClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRequirementDetail
    {
        public int JobRequirementDetailId { get; set; }
        public int JobRequirementId { get; set; }
        public string JobRequirementDetails { get; set; }
        public int PostJobId { get; set; }
    
        public virtual JobRequirement JobRequirement { get; set; }
        public virtual PostJob PostJob { get; set; }
    }
}
