//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobhundClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostJob()
        {
            this.JobRequirementDetails = new HashSet<JobRequirementDetail>();
        }
    
        public int PostJobId { get; set; }
        public int UserId { get; set; }
        public int CompanyId { get; set; }
        public int JobCategoryId { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public int MinSalary { get; set; }
        public int Maxsalary { get; set; }
        public int Vecancey { get; set; }
        public string Location { get; set; }
        public System.DateTime PostDate { get; set; }
        public System.DateTime ApplicationLastdate { get; set; }
        public System.DateTime LastDate { get; set; }
        public int JobStatusId { get; set; }
        public int JobNatureId { get; set; }
        public string WebUrl { get; set; }
    
        public virtual JobCategory JobCategory { get; set; }
        public virtual JobNature JobNature { get; set; }
        public virtual JobStatu JobStatu { get; set; }
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRequirementDetail> JobRequirementDetails { get; set; }
    }
}
